Mitglieder auf der Webiste per Docker container updaten
codeformuenster/codeformuenster.github.io pull request #66
Opened 2019-02-14 00:36 UTC by ScholliYT

Hallo zusammen,

habe mal etwas rumgebastelt um ein "automatisches update" der Mitgliederanzeige auf der Website einzuleiten. 

![screenshot_245](https://user-images.githubusercontent.com/12571895/52753813-78683180-2ff8-11e9-86f9-b9d1f2d74083.png)

Schritte zum Nachmachen:
1. **Git-Hub API Key** in update_members_docker.sh hinter `"GITHUBTOKEN=`" eintragen. Diese muss nur die Permission  `repo:status` haben. Könnt ihr [hier](https://github.com/settings/tokens) erstellen.
2. **Container builden** mit dem script `containers/make_docker_container.sh`
3. Update script ausüfhren: `update_members_docker.sh`

Definitv müsste sich das ganze hier mal jemand angucken, der mehr Ahnung von docker hat ^^
Die members.json Datei wieder aus dem Container raus zu bekommen, kriegt man bestimmt schöner hin. Meine lösung mit dem `update_members_docker.sh` script finde ich nicht so gut.

2019-02-19 17:42 UTC, ubergesundheit commented
Schau dir mal für docker host volume mounts an. Dokumentation gibts [hier](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems). Und zwar kannst du die Datei die du updatest einfach mit `-v` in den container einhängen. Dann noch am besten den container auch mit `--rm` starten, dann bleibt der container nachher auch nicht im system hängen

2019-03-01 10:40 UTC, ScholliYT commented
Habe den Docker Befehl jetzt nochmal angepasst. Funktioniert auch wunderbar.
`docker run --name update_members --rm -it -e GITHUBTOKEN=TOKEN -v "$PWD"/json/members.json:/app/json/members.json  update-members`

Jetzt muss ich nur noch gucken wie ich die Erstellung des Containers schöner hinbekomme.

2019-03-13 13:27 UTC, tomsrocket commented
Mir fiel auf, dass das updaten der members auch eh schon in der "update-data.php" gemacht wird. 
Da werden ja quasi alle Datendateien geschrieben die von der Seite benötigt werden: 
https://github.com/codeformuenster/codeformuenster.github.io/blob/master/update-data.php#L114

Dieser PR zeigt trotzdem sehr cool wie man das als isolierten Prozess mit Docker machen kann, insofern würde ich das trotzdem mit reinnehmen, das kann man dann ja z.B. als cronjob einrichten.

@ScholliYT Bist Du denn soweit damit fertig, sollen wir das mergen?

2019-03-13 17:16 UTC, ScholliYT commented
Ja, genau. `update-data.php` Skript kann eig. schon alles notwendige. Ich finde nur die Idee der Isolierten Prozesse auch ganz interessant. Wenn diese PR hier gescheit funktioniert würde ich mich auch nochmal ransetzten und das ganze in einem weiteren Container für die Repositories machen.

@tomsrocket Meinetwegen kann diese PR gemergt werden.

2019-03-14 08:03 UTC, ubergesundheit commented
du solltest auf jeden Fall noch deinen Github token per forcepush aus dem branch raus nehmen und eine Anleitung schreiben

2019-03-14 08:04 UTC, ubergesundheit requested changes
Github token rausnehmen und Readme anpassen, danke

2019-03-14 18:05 UTC, ScholliYT commented
Ups ^^ Den GitHub Token wollte ich eigentlich auch nicht pushen. Aber danke für den Hinweis.

2019-03-26 07:08 UTC, ubergesundheit approved these changes

2019-03-26 13:44 UTC, ScholliYT commented
@ubergesundheit wer ist denn hier Ansprechpartner, wenn dieser Docker Container automaitsch (jede Woche) laufen soll?

2019-03-26 18:37 UTC, ubergesundheit commented
Gibt zwei Möglichkeiten die mir einfallen:

1. Du schreibst passende Kubernetes manifeste für nen Cronjob auf dem Cluster, @webwurst ist da der Ansprechpartner
2. Du bastelst dir was mit nem kostenlosten CI/CD Anbieter (zb Travis)

2019-04-19 20:04 UTC, merged